# Generated by Django 4.1 on 2023-03-09 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Blog",),
    ]
