# Generated by Django 4.1 on 2023-03-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment", name="author", field=models.TextField(max_length=30),
        ),
    ]
