# Generated by Django 4.1 on 2023-03-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_comment_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment", name="author", field=models.CharField(max_length=30),
        ),
    ]
