# Generated by Django 4.1 on 2023-03-12 05:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_comment_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
