# Generated by Django 4.1 on 2023-03-12 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user", "0006_rename_post_comment_blog"),
    ]

    operations = [
        migrations.AlterModelOptions(name="comment", options={"ordering": ["-time"]},),
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
