# Generated by Django 4.1 on 2023-03-15 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_alter_blog_options_blog_title_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="category",
            field=models.CharField(default="testing", max_length=40),
        ),
        migrations.AlterField(
            model_name="blog", name="title_tag", field=models.CharField(max_length=50),
        ),
    ]
