# Generated by Django 4.1 on 2023-03-16 11:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user", "0012_category_alter_blog_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="likes",
            field=models.ManyToManyField(
                related_name="blog_likes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
