# Generated by Django 4.1 on 2023-03-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0014_alter_blog_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog", name="content", field=models.TextField(default=""),
        ),
    ]
