# Generated by Django 4.1 on 2023-03-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0017_blog_snippet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog", name="snippet", field=models.TextField(max_length=100),
        ),
    ]
