# Generated by Django 4.1 on 2023-03-18 06:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user", "0018_alter_blog_snippet"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="views",
            field=models.ManyToManyField(
                related_name="blog_views", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
