# Generated by Django 4.1 on 2023-03-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0020_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
